version: '3.8'
services:
  api:
    build: .               
    ports:
      - '3000:3000'          
    env_file:
      - .env                
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare
    ports:
      - '5432:5432'

  mongo:
    image: mongo:5
    ports:
      - '27017:27017'
